export const routeData = [
  { id: 1, destination: 'Hà Nội', description: 'Thủ đô ngàn năm văn hiến' },
  { id: 2, destination: 'Hồ Chí Minh (Sài Gòn)', description: 'Thành phố năng động nhất Việt Nam' },
  { id: 3, destination: 'Hải Phòng', description: 'Thành phố cảng biển lớn' },
  { id: 4, destination: 'Đà Nẵng', description: 'Thành phố đáng sống bên sông Hàn' },
  { id: 5, destination: 'Cần Thơ', description: 'Thủ phủ miền Tây sông nước' },
  { id: 6, destination: 'An Giang', description: 'Miền đất Bảy Núi linh thiêng' },
  { id: 7, destination: 'Bà Rịa - Vũng Tàu', description: 'Biển xanh và dầu khí' },
  { id: 8, destination: 'Bạc Liêu', description: 'Xứ sở công tử Bạc Liêu' },
  { id: 9, destination: 'Bắc Giang', description: 'Vùng đất quan họ và vải thiều' },
  { id: 10, destination: 'Bắc Kạn', description: 'Miền núi yên bình với hồ Ba Bể' },
  { id: 11, destination: 'Bắc Ninh', description: 'Cái nôi của dân ca quan họ' },
  { id: 12, destination: 'Bến Tre', description: 'Xứ dừa miền Tây' },
  { id: 13, destination: 'Bình Dương', description: 'Trung tâm công nghiệp phía Nam' },
  { id: 14, destination: 'Bình Định', description: 'Miền đất võ và biển Quy Nhơn' },
  { id: 15, destination: 'Bình Phước', description: 'Miền đất cao su bạt ngàn' },
  { id: 16, destination: 'Bình Thuận', description: 'Biển xanh cát trắng Mũi Né' },
  { id: 17, destination: 'Cà Mau', description: 'Điểm cực Nam của Tổ quốc' },
  { id: 18, destination: 'Cao Bằng', description: 'Thác Bản Giốc hùng vĩ' },
  { id: 19, destination: 'Đắk Lắk', description: 'Thủ phủ cà phê Buôn Ma Thuột' },
  { id: 20, destination: 'Đắk Nông', description: 'Miền đất đỏ bazan trù phú' },
  { id: 21, destination: 'Điện Biên', description: 'Chiến thắng lịch sử Điện Biên Phủ' },
  { id: 22, destination: 'Đồng Nai', description: 'Cửa ngõ công nghiệp của miền Nam' },
  { id: 23, destination: 'Đồng Tháp', description: 'Đất sen hồng miền Tây' },
  { id: 24, destination: 'Gia Lai', description: 'Phố núi Pleiku mờ sương' },
  { id: 25, destination: 'Hà Giang', description: 'Cao nguyên đá Đồng Văn hùng vĩ' },
  { id: 26, destination: 'Hà Nam', description: 'Miền đất giáp Thủ đô' },
  { id: 27, destination: 'Hà Tĩnh', description: 'Quê hương núi Hồng sông La' },
  { id: 28, destination: 'Hải Dương', description: 'Miền đất địa linh nhân kiệt' },
  { id: 29, destination: 'Hậu Giang', description: 'Miền sông nước trù phú' },
  { id: 30, destination: 'Hòa Bình', description: 'Vùng đất của người Mường' },
  { id: 31, destination: 'Hưng Yên', description: 'Phố Hiến xưa vang bóng' },
  { id: 32, destination: 'Khánh Hòa', description: 'Biển Nha Trang xanh ngắt' },
  { id: 33, destination: 'Kiên Giang', description: 'Phú Quốc – đảo ngọc Việt Nam' },
  { id: 34, destination: 'Kon Tum', description: 'Vùng đất Tây Nguyên hoang sơ' },
  { id: 35, destination: 'Lai Châu', description: 'Đỉnh núi Pu Si Lung hùng vĩ' },
  { id: 36, destination: 'Lâm Đồng', description: 'Thành phố Đà Lạt mộng mơ' },
  { id: 37, destination: 'Lạng Sơn', description: 'Xứ Lạng biên cương' },
  { id: 38, destination: 'Lào Cai', description: 'Sa Pa mờ sương' },
  { id: 39, destination: 'Long An', description: 'Cửa ngõ miền Tây Nam Bộ' },
  { id: 40, destination: 'Nam Định', description: 'Miền quê văn hiến' },
];
